### ISSUE TITLE
Change from `new Date().getTime()` to `microtime.nowDouble()` broke the metrics scale.

### ISSUE THREAD

**Issue by jbarreneche** [restorando/monolith#10]
`microtime.nowDouble()` returns seconds since epoch, while the previous `new Date().getTime()` where ms since epoch.

```node
> microtime = require('microtime')
{ now: [Function], nowDouble: [Function], nowStruct: [Function] }
> new Date().getTime()
1492509743127
> microtime.nowDouble()
1492509748.469305
```

**Comment by jfresco** [comment]
Let me get this straight: it is expected that que request time header (i.e. `X-Queue-Start`) comes in seconds. So it is correct to make the substraction with the current time in seconds, but the final result should be multiplied by 1000, in order to report the elapsed time in ms:

```js
const now = microtime.nowDouble() // Seconds since epoch
const diff = now - queueStart // both times are in seconds
return diff * 1000 // I need to report elapsed time in ms
```

I'm based on [this](https://github.com/restorando/statue/pull/13/files?diff=split#diff-b25f4776160d9b5c03b1047bdf343293R73).

Am I right?

**Comment by jbarreneche** [comment]
@jfresco yes, and also when you started using `microtime` the scale for `requestDuration` was changed (which previously was in milliseconds and now is in seconds)
